---
name: Verify NSD configuration
description: Verify NSD nsd.conf and zonefile configuration

inputs:
  zone_directory:
    description: directory containing zonefiles to validate
  zone_pattern:
    description: glob pattern of zonefiles to check
    default: '*.zone'

outputs:
  errors:
    description: any errors reported by the validation process

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.zone_directory }}
    - ${{ inputs.zone_pattern }}
